AUTHORS.rst, Pipfile, neurokit2/__init__.py, neurokit2/data/__init__.py, neurokit2/data/find_creation_date.py, neurokit2/data/read_acqknowledge.py, setup.py, tox.ini
added new functions to data 
add bioread into deps
=> add read_acqknowledge and etc

AUTHORS.rst
add Chuan-Peng as a contributor.
This PR aims at adding this feature...
I changed the `foo` function so that ...
=> Count me in (my first PR)

neurokit2/rsp/rsp_clean.py, neurokit2/rsp/rsp_findpeaks.py, neurokit2/rsp/rsp_plot.py, neurokit2/rsp/rsp_process.py, neurokit2/rsp/rsp_rate.py, neurokit2/signal/signal_interpolate.py
`rsp_clean()`
* added docstrings
`rsp_findpeaks()`
* added docstrings
* changed names of returned attributed to be more specific
`rsp_rate()`
* added doctrings
* added return_amplitude parameter / flag
`rsp_process()`
* added docstrings
* changed names of returned attributed to be more specific
`rsp_plot()`
* added docstrings
`signal_interpolate()`
* removed unused paramter from docstrings
All functions in the `rsp` module run error free on my machine. Will write proper tests asap.
```
import neurokit2 as nk
import numpy as np
rsp = np.loadtxt(r"testsignal_rsp.txt")
rsp_cleaned = nk.rsp_clean(rsp)
extrema_signal, extrema = nk.rsp_findpeaks(rsp_cleaned)
rate = nk.rsp_rate(extrema, return_amplitude=False)
summary, _ = nk.rsp_process(rsp)
nk.rsp_plot(summary)
```
=> Added docstrings to functions in rsp module

neurokit2/ecg/ecg_simulate.py, neurokit2/eda/eda_simulate.py, neurokit2/emg/emg_simulate.py, neurokit2/rsp/rsp_simulate.py
=> Fixing random seeds during data simulation

AUTHORS.rst
@DominiqueMakowski : Thanks for the invitation. :smile:
=> Adds my name to the list of contributors

neurokit2/rsp/__init__.py, neurokit2/rsp/rsp_amplitude.py, neurokit2/rsp/rsp_clean.py, neurokit2/rsp/rsp_findpeaks.py, neurokit2/rsp/rsp_plot.py, neurokit2/rsp/rsp_process.py, neurokit2/rsp/rsp_rate.py, tests/tests_rsp.py
Adressing #64 I made the following changes to the `rsp` module
+ `rsp_amplitude()`: stand-alone function for computation of breathing amplitude
+ `test_rsp_amplitude()`
+ `rsp_rate()`: removed computation of breathing amplitude
+ `rsp_process()`: now calls `rsp_amplitude()` instead of `rsp_rate()` for computation of breathing amplitude
+ `rsp_plot()`: some minor changes to make plotting more consistent with `ecg_plot()`
=> Fixing error in breathing rate calculation

neurokit2/rsp/rsp_plot.py
tiny PR to tame the mostly benign obsessive-compulsive tendencies 😊
=> Added inhalation and exhalation to the axis-legend

README.rst, neurokit2/ecg/ecg_fixpeaks.py, neurokit2/ecg/ecg_plot.py, neurokit2/signal/signal_rate.py, scripts/ecg_fixpeaks.ipynb, tests/tests_ecg.py
Fixed some additional occurrences of the indexing issue describes in #132. This did not affect the tests on my machine.
Also renamed an argument of `ecg_fixpeaks()`.
=> Corrected mean calculation by changing indexing

neurokit2/ecg/ecg_delineate.py, neurokit2/ecg/ecg_peaks.py
Fix a small bug in the ecg_fixpeaks function, which cause CI to fail.
=> Bugfix: wrong ecg_fixpeaks keyword argument lists

tests/tests_ecg_delinator.py
Small fix to have ecg_delinate tests passing on python3.5
=> Do not use f-string as it is not supported by python3.5

neurokit2/signal/signal_filter.py, tests/tests_ecg.py, tests/tests_signal.py
=> Re-implemented powerline filter

docs/conf.py, docs/environment.yml
This PR aims at fixing doc build on readthedocs.
=> Remove 'unmockable' modules

neurokit2/ecg/ecg_simulate.py, neurokit2/eda/eda_simulate.py, neurokit2/emg/emg_simulate.py, neurokit2/rsp/rsp_simulate.py, neurokit2/signal/signal_distort.py, neurokit2/signal/signal_simulate.py
Adressing #169 
Try with
```python
import neurokit2 as nk
nk.signal_simulate(duration=10, sampling_rate=100, frequency=100, amplitude=0.5, silent=False)
nk.signal_simulate(duration=10, sampling_rate=100, frequency=.01, amplitude=0.5, silent=False)
```
=> Hush up those warnings

neurokit2/signal/signal_fixpeaks.py
As discussed with Jan,
- Fixed patches of the polygon described in the paper (better visualization).  [picture]
- Adjust limits to the threshold plots.
=> fix variable-patches

neurokit2/complexity/fractal_correlation.py
This PR aims to remove an unused module [here](https://github.com/neuropsychology/NeuroKit/blob/dev/neurokit2/complexity/fractal_correlation.py). Issue #220 
Removed the import of the module
=> Removed unused module

.github/CONTRIBUTING.rst, .github/workflows/style.yml, docs/conf.py, neurokit2/__init__.py, neurokit2/benchmark/__init__.py, neurokit2/benchmark/benchmark_ecg.py, neurokit2/benchmark/benchmark_utils.py, neurokit2/complexity/complexity_dimension.py, neurokit2/complexity/complexity_embedding.py, neurokit2/complexity/complexity_simulate.py, neurokit2/complexity/utils.py, neurokit2/ecg/ecg_clean.py, neurokit2/ecg/ecg_delineate.py, neurokit2/ecg/ecg_findpeaks.py, neurokit2/ecg/ecg_rsa.py, neurokit2/eda/eda_intervalrelated.py, neurokit2/eda/eda_phasic.py, neurokit2/emg/emg_intervalrelated.py, neurokit2/rsp/rsp_simulate.py, neurokit2/signal/__init__.py, neurokit2/signal/signal_changepoints.py, neurokit2/signal/signal_decompose.py, neurokit2/signal/signal_filter.py, neurokit2/signal/signal_fixpeaks.py, neurokit2/signal/signal_formatpeaks.py, neurokit2/signal/signal_recompose.py, neurokit2/stats/__init__.py, neurokit2/stats/mutual_information.py
=> [feature] SSA-based Single-channel decomposition methods

.github/workflows/checks.yml, docs/readme/README_examples.py
matplotlib use agg for server use. Install all deps in install step
=> Attempt to fix failing CI

neurokit2/signal/signal_plot.py
Improve `signal_plot()` features
=> [features] Improve signal_plot()

.github/workflows/style.yml, neurokit2/signal/signal_interpolate.py
Trigger style action on push to all branches and PR only to master
=> [CI] update style workflow

AUTHORS.rst, tests/tests_ecg.py
Pull Request https://github.com/neuropsychology/NeuroKit/pull/303
Apologies for the additional PR, I had a mistake in the contributors file markup.
Additionally, I added in a simple test case to check for issue https://github.com/neuropsychology/NeuroKit/issues/304.
Here are some things to check before creating the PR.
=> ecg_intervalrelated test case, fixed contributors spacing

AUTHORS.rst, neurokit2/rsp/rsp_analyze.py, neurokit2/rsp/rsp_rrv.py
1000 hz sampling rate
```
>>> import neurokit2 as nk
>>>
>>> rsp = nk.rsp_simulate(duration=90, respiratory_rate=15)
>>> rsp, info = nk.rsp_process(rsp)
>>> rrv = nk.rsp_rrv(rsp, show=True) 
```
32 hz sampling rate
```
>>> import neurokit2 as nk
>>> from scipy import signal
>>> rsp = nk.rsp_simulate(duration=90, respiratory_rate=15)
>>> rsp = signal.resample(rsp, int((len(rsp) / 1000) * 32))
>>> rsp, info = nk.rsp_process(rsp, sampling_rate=32)
>>> rrv = nk.rsp_rrv(rsp, show=True, sampling_rate=32) 
```
the results is different due to statically defined sampling rate
i change it to dynamic values
I changed some respiration functions for catching a bug
=> respiration sampling rate issue

neurokit2/hrv/hrv_nonlinear.py, tests/tests_hrv.py
Addresses Issue #344 
I updated the consecutive concatenation to be more robust
=> [Fix] #344 with corresponding test

neurokit2/hrv/hrv.py, neurokit2/hrv/hrv_time.py, neurokit2/stats/summary.py
This PR aims at adding this feature: Error bars in the summary plot method to illustrate standard error of each bin.
I changed the function "Summary_Plot" to take in an bool errorbar parameter that if true will display the error bar and if false will not display errorbar.
- [ X] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [X ] My PR is targetted at the **dev branch** (and not towards the master branch).
- [X ] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
=> [Feature] Updated Error Bar Request

neurokit2/ecg/ecg_findpeaks.py
Fix bug array out of bounds ecg_findpeaks_rodrigues
Solve issue #465 by checking the size of the array before stage
=> Bug fix ecg_findpeaks_rodrigues

neurokit2/ecg/ecg_findpeaks.py, neurokit2/ecg/ecg_peaks.py
This PR aims at fixing a typo which leads user(actually, me) use this module incorrectly.
fix typo: pamtompkins -> pantompkins
=> docs typo: pamtompkins -> pantompkins

NEWS.rst, neurokit2/misc/__init__.py, neurokit2/misc/intervals_to_peaks.py
to initiate `intervals_to_peaks()` convenience function
=> convert intervals to peaks

AUTHORS.rst, neurokit2/complexity/__init__.py, neurokit2/complexity/fractal_dfa.py, neurokit2/hrv/hrv_nonlinear.py, neurokit2/rsp/rsp_rrv.py, tests/tests_complexity.py, tests/tests_ecg.py, tests/tests_hrv.py
As discussed in https://github.com/neuropsychology/NeuroKit/issues/206, @LRydin has identified an issue with the implementation of MFDFA and has started the fix for it. 
As we are urgently in need to use this function for our upcoming analysis, I have *blatantly* made this PR on @LRydin's behalf 😅 to continue working on it. Hope it's alright with you and please do take a look whenever you have some time! 😀 
=> DFA fix from LRydin's fork

neurokit2/hrv/hrv_time.py
=> Fix geometric indices of HRV

NEWS.rst, neurokit2/complexity/fractal_dfa.py, neurokit2/complexity/fractal_higuchi.py, neurokit2/hrv/hrv_time.py
=> Sanitize HRV outputs

NEWS.rst, neurokit2/rsp/rsp_amplitude.py, neurokit2/rsp/rsp_peaks.py, neurokit2/rsp/rsp_process.py, neurokit2/rsp/rsp_rate.py, neurokit2/rsp/rsp_rrv.py, tests/tests_rsp.py
Have respiratory rate computed based on troughs instead of peaks as discussed in #528
=> Compute respiration rate based on troughs

neurokit2/complexity/complexity_embedding.py, neurokit2/complexity/complexity_recurrence.py, neurokit2/complexity/complexity_rqa.py, neurokit2/complexity/fractal_correlation.py, neurokit2/complexity/optim_complexity_delay.py, neurokit2/complexity/optim_complexity_tolerance.py, neurokit2/data/read_bitalino.py
=> Support for reading multiple devices + events in `read_bitalino`

neurokit2/signal/signal_rate.py
Clarify rate is per minute
I changed the docstring for the signal_rate function to clarify rate is per minute (60 seconds).
=> [Docs] Update signal_rate.py docstring for return param

neurokit2/ppg/ppg_findpeaks.py, neurokit2/signal/signal_fixpeaks.py
=> Peaks fixes in `ppg` and `ecg`

neurokit2/bio/bio_analyze.py, neurokit2/ecg/ecg_analyze.py, neurokit2/ecg/ecg_eventrelated.py, neurokit2/epochs/eventrelated_utils.py, neurokit2/rsp/rsp_analyze.py, neurokit2/rsp/rsp_eventrelated.py
It was a confusing argument that we implemented for internal reasons but there is no reason to keep maintaining it.
=> [Breaking] Remove subepoch_rate argument in bio_analyze

neurokit2/signal/signal_fixpeaks.py
=> signal_fixpeaks() allow kwargs

docs_readthedocs/examples/hrv.ipynb
This PR fixes a small typo in the HRV example.
Replace the comment
=> Fix typo in HRV example

neurokit2/hrv/hrv_time.py
The feature name in the comment is hcvnn, but the code is mcvnn
This is a template for making a pull-request. You can remove the text and sections and write your own thing if you wish, just make sure you give enough information about how and why. If you have any issues or difficulties, don't hesitate to open an issue so we can help.
This PR aims at adding this feature...
I changed the `foo()` function so that ...
=> [Docs] Fix typo in hrv_time

neurokit2/complexity/fractal_dfa.py, neurokit2/misc/find_knee.py, tests/tests_complexity.py
https://github.com/LRydin/MFDFA/issues/33
=> [Feature] MFDFA: allow for q=0

neurokit2/hrv/hrv_time.py
Modify the hrv_time() function such that the documentation reflects how RMSSD is computed.
(Made a separate PR from https://github.com/neuropsychology/NeuroKit/pull/698 since this is only documentation changes)
I changed the `hrv_time()` function as follows:
1. Changed documentation of RMSSD and CVSD so that RMSSD is defined as the root mean square of successive differences rather than the root mean sum of successive differences
=> [Docs] Fix documentation of RMSSD

neurokit2/ecg/ecg_findpeaks.py, neurokit2/ecg/ecg_peaks.py, tests/tests_ecg.py
As discussed in [Issue 700](https://github.com/neuropsychology/NeuroKit/issues/700), this PR attributes the Martinez R-peak detection algorithm to the following paper:
_Martínez JP, Almeida R, Olmos S, Rocha AP, Laguna P. A wavelet-based ECG delineator: evaluation on standard databases. IEEE Trans Biomed Eng 2004;51:570–581._
I changed the following functions to update the attribution of this algorithm from 'Martinez2003' to 'Martinez2004':
- [`ecg_findpeaks`](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/ecg/ecg_findpeaks.py)
- [`ecg_peaks`](https://github.com/neuropsychology/NeuroKit/blob/master/neurokit2/ecg/ecg_peaks.py)
Specific details of the changes are given in [Issue 700](https://github.com/neuropsychology/NeuroKit/issues/700)
Here are some things to check …
=> [Breaking] `martinez2003` method for ECG peak detection renamed `martines2004`

neurokit2/data/read_bitalino.py
currently read_bitalino breaks when there are no annotations inputted as events
=> fix read_bitalino

neurokit2/signal/signal_findpeaks.py
- fix _signal_findpeaks_distances
- Closes #733 
- I changed the `_signal_findpeaks_distances` calculates two distances (distance between i-th and (i-1)-th elements and i-th and (i+1)-th elements) and selects the smaller one.
=> [fix] fix _signal_findpeaks_distances (#733)

.github/workflows/docs-build.yml, .github/workflows/docs-check.yml, AUTHORS.rst, neurokit2/ecg/ecg_clean.py, neurokit2/ecg/ecg_findpeaks.py, neurokit2/ecg/ecg_peaks.py, setup.py
This PR aims at adding the feature mentioned here #744. 
I implemented a method for R peak detection that uses an ECG to visibility graph transformation according to this [article](https://ieeexplore.ieee.org/document/9871266).
=> [Feature] ECG R-Peak detection using visibility graphs 

neurokit2/misc/report.py, neurokit2/ppg/ppg_methods.py, neurokit2/rsp/__init__.py, neurokit2/rsp/rsp_methods.py, neurokit2/rsp/rsp_process.py, neurokit2/rsp/rsp_rvt.py
This PR is based on the discussion of [this thread](https://github.com/neuropsychology/NeuroKit/pull/750) and builds on my previous PR #754 . Let me know if I should point the PR to a different branch.
The goal here is to provide rsp_methods and follows the template made by @danibene  (thank you!) in ppg_methods, which was also refactored.
I likely won't have time for rsp_report in November, so somebody else might take over or I do it in December.
- Creation of the rsp_methods function based on ppg_methods
- Refactor of ppg_methods and report.py
=> [Feature] add rsp_methods (basis for rsp reports)

neurokit2/rsp/rsp_process.py, neurokit2/rsp/rsp_rvt.py
(New branch because I could not add to the other branch. Also I made a PR from the wrong branch before, my bad.)
This PR is a follow-up on the discussions in [this thread](https://github.com/neuropsychology/NeuroKit/pull/750) to augment RRV RVT.
- I only did the minimum in the docs to also show it, maybe there is a bigger change needed to make it more clear with the different modes.
- I did not do profiling, but I had a look at the method and I refactored parts of the for-loop, which should now make it easier to parallelize (if needed). Also, some functions were changed and almost everything is now either managed by a nk or np function, which are faster than anything I could come up with.
- I did not do thorough testing, but they should be identical from my understanding and I will make …
=> [Fix] RVT Improvements

neurokit2/ecg/ecg_delineate.py
This is a template for making a pull-request. You can remove the text and sections and write your own thing if you wish, just make sure you give enough information about how and why. If you have any issues or difficulties, don't hesitate to open an issue so we can help.
This PR aims at adding this feature...
I changed the `foo()` function so that ...
=> [Fix] fix edgecase in ecg_delineate()

docs/installation.rst, neurokit2/complexity/__init__.py, neurokit2/complexity/entropy_angular.py, neurokit2/complexity/entropy_differential.py, neurokit2/complexity/entropy_sample.py
#806 
- Nardelli, M., Greco, A., Sebastiani, L., & Scilingo, E. P. (2022). ComEDA: A new tool for stress assessment based on electrodermal activity. Computers in Biology and Medicine, 150, 106144.
Note: I didn't implement comEDA straight out of the box as I have yet to be convinced by its utility (and on which signal is it better to compute it).
=> [Feature] Add Angular Entropy (AngEn) that can be used to get comEDA 

neurokit2/eda/eda_phasic.py, tests/tests_eda.py
https://github.com/neuropsychology/NeuroKit/issues/807
The implementation is largely based on https://github.com/yskong224/SprasEDA-Python/tree/main.
=> [Feature] Add sparsEDA algorithm for phasic / tonic EDA decomposition

neurokit2/hrv/hrv_frequency.py
This PR aims at adding total power as an HRV feature. See https://github.com/neuropsychology/NeuroKit/issues/821
I changed the `hrv_frequency()` function so that `total_power` is added to the output, called `TP`.
=> [Feature] add total power as HRV feature

neurokit2/signal/signal_power.py, tests/tests_stats.py
This PR aims at adding a test for the cor() function inside stats/correlation.py in order to improve code coverage.
The function test_cor() was added. It contains examples of arrays whose correlation is known.
[Pearson](https://en.wikipedia.org/wiki/Pearson_correlation_coefficient#Geometric_interpretation)
[Spearman](https://en.wikipedia.org/wiki/Spearman%27s_rank_correlation_coefficient#Example)
[Kendall (page 3)](https://personal.utdallas.edu/~herve/Abdi-KendallCorrelation2007-pretty.pdf)
For each of the 3 methods, array pairs are passed as arguments into the cor function and the computed result is compared with the known result.
A separate negative test checks whether incorrect inputs to the 'method' argument are caught.
Here are some things to check before creating the PR. If you …
=> [Feature] Test for stats/correlation.py

neurokit2/ecg/ecg_quality.py
=> [Docs] typo in ecg_quality docstring

neurokit2/rsp/rsp_rate.py, tests/tests_rsp.py
Co-authored-by: Johannes Herforth  <DerAndereJohannes+25019880@users.noreply.github.com>
closes #1067 
I changed the `rsp_rate()` function so that troughs can be one of those type: list, np.array, dict, pd.Series, pd.DataFrame, and added a `test_rsp_rate()` to `tests_rsp.py`
=> [Fix] rsp_rate function 

neurokit2/ecg/ecg_process.py
I was checking the doc and found that the ECG_Phase_Ventricular is missing in the return variable of ecg_process function.
I added the ECG_Phase_Ventricular and also added the info about the atrial or ventricular for the phase. 
- [X ] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [X ] My PR is targeted at the **dev branch** (and not towards the master branch).
- [X ] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
=> Clarify ECG phase descriptions
