- neurokit2/ecg/ecg_fixpeaks.py
- tests/tests_ecg.py
Fixed small but critical error in `ecg_fixpeaks()`. The fix is swapping the conditionals on line 201 and 209 (the other changes are mostly cosmetic). Also adapted one test that was affected by the change.
> fixed error in artifact classification

- neurokit2/rsp/rsp_amplitude.py
- neurokit2/rsp/rsp_rate.py
- neurokit2/signal/signal_interpolate.py
Related to #122 I propose the commited changes to `signal_interpolate()`. I adapted the fucntions calling `signal_interpolate()` within the `rsp` module. The problem described in #122 seems fixed (confirmed by looking at plotted output of `rsp_process()` before and after the fix). Note however that other modules also rely on `signal_interpolate()` and that in those modules stuff probably breaks now.
> Proposal to simplify signal interpolation

- tests/tests_rsp.py
the signals in `test_rsp_simulated()` were generated with a new seed on every run since the seed was not passed on to `rsp_simulate()`.
> fixing random seeds

- AUTHORS.rst
- neurokit2/ecg/ecg_findpeaks.py
Uses a (inclusive )scan to precompute the individual means of the signal. Instead of computing the a mean every time(Yields about x10 performance.)
I changed the `_ecg_findpeaks_MWA `  in  `neurokit2/ecg/ecg_findpeaks.py`
> Pre-compute means in _ecg_findpeaks_MWA

- neurokit2/ecg/ecg_hrv.py
- neurokit2/rsp/rsp_rrv.py
- neurokit2/signal/signal_power.py
- neurokit2/signal/signal_psd.py
To determine the window_length, the following steps were made:
A nperseg long enough to capture at least 2 cycles of lowest frequency:
```
if min_frequency == 0:
min_frequency = 0.001  # sanitize lowest frequency
if window is not None:
nperseg = int(window * sampling_rate)
else:
nperseg = int((2 / min_frequency) * sampling_rate)
```
However, since our signals are mostly sampled at high frequency (1000-4000Hz) and min_frequency is often very low (~0 Hz 😅 ), nperseg can be super huge, sometimes longer than duration of signal. 
```
if nperseg > len(signal) / 2:
print("Neurokit warning: signal_psd(): The duration of recording is too short to support a sufficiently long window for high frequency resolution. Consider using a longer recording or increasing the `min_frequency`")
nperseg = …
```
> Changes to Welch method in signal_psd()

- AUTHORS.rst
- neurokit2/hrv/hrv_nonlinear.py
This PR aims at fixing a potential bug in the computation of non-linear HRV features (hrv_nonlinear.py)
According to Brennan et al. 2001 (https://doi.org/10.1109/10.959330, Eq. 12) SD2 is computed as: sqrt(2 * std(RR)^2 - 0.5 * std(SD)),
where RR = RR intervals, SD = successive differences
In the code, SD2 is computed as: sqrt(2 * std(SD)^2 - 0.5 * std(SD))
I changed the `hrv_nonlinear()` function so that SD2 (and SD2/SD1, accordingly) is computed correctly.
Here are some things to check before creating the PR.
> Fixed potential bug in hrv_nonlinear.py

- neurokit2/hrv/hrv_nonlinear.py
- tests/tests_ecg.py
- tests/tests_hrv.py
I changed the SD2/SD1 ratio to SD1/SD2 since other implementations and references also compute this feature.
Here are some things to check before creating the PR.
> [fix] hrv_nonlinear: changed SD2/SD1 ratio of Poincaré to SD1/SD2

- AUTHORS.rst
- benchmarks/ecg_preprocessing/README.md
- docs/benchmarks/ecg_preprocessing.rst
- docs/conf.py
- docs/environment.yml
Partially resolves #275.
Use the `mdinclude` directive of m2r, per https://github.com/readthedocs/recommonmark/issues/191#issuecomment-622369992 for including benchmarks/ecg_preprocessing/README.md on the Benchmarks page. To make this work, I had to additionally:
* Use HTML for any hyperlinks in bold/italics;
* Remove blank lines from references div; and
* Relative link figures from docs directory, i.e. prepend ../../benchmarks/ecg_preprocessing to image paths.
The latter does not break images on the [modified README](benchmarks/ecg_preprocessing/README.md) when viewed on GitHub as the relative link coincidentally resolves the same file from both locations.
> [docs] Use of mdinclude directive to add .md files to sphinx docs

- AUTHORS.rst
- neurokit2/ecg/ecg_analyze.py
The behavior of `ecg_analyze(df, sampling_rate=500, method="interval-related")` should be identical to calling `ecg_intervalrelated(df, sampling_rate=500)`.
I added the `sampling_rate` kwarg to all `ecg_intervalrelated` calls within `ecg_analyze`.
Here are some things to check before creating the PR.
> ecg_analyze should pass sampling_rate to ecg_intervalrelated call

- AUTHORS.rst
- neurokit2/ecg/ecg_delineate.py
- tests/tests_ecg_delineate.py
Fix ecg_delineate bug described in neuropsychology/NeuroKit#309
The bug reported is fixed in line 668-669 by returning a list with a np.nan instead of an empty list in `_find_tppeaks`. Additionally, I changed the type of array in `_peaks_delineator` and in `_onsets_offsets_delineator` to object as a an array with np nans cannot be converted to int. Finally, in `_onsets_offsets_delineator` if the peak is a np.nan now it appends a np.nan to the onsets and offsets list and don't do any calculation for this peak.
The problem is that by adding np.nans to the arrays, it forces the array to be a float array instead of int, which means that before using the indices for slicing you have to convert them to int. Another option is to convert the arrays into object arrays )which I did) but idk if it …
> [Fix] ecg_delineate CWT mode crash when no consecutive tp peaks found

- neurokit2/rsp/rsp_intervalrelated.py
In the RSP_Amplitude_Mean there was a mention to 'heart'.
> [Fix] corrected 'heart' with 'respiratory' in docstring

- neurokit2/microstates/microstates_segment.py
- neurokit2/stats/cluster.py
- neurokit2/stats/cluster_quality.py
Microstates list:
Tried to implement it in clusters_quality but gives funny results. (especially the normalization part doesn't work).
Implementations from https://github.com/Frederic-vW/eeg_microstates/blob/master/eeg_microstates.py#L602 and https://github.com/wmvanvliet/mne_microstates/blob/master/microstates.py#L126 (added my version of both in clusters_quality) give very different results. Also, it would be good to get the GEV per microstate, which currently isn't computed it seems.
> [Fix] Review microstate implementations

- neurokit2/eda/eda_process.py
When the given signal has Index set then Pandas's concat is not working correctly
[Problem] (https://stackoverflow.com/questions/32801806/pandas-concat-ignore-index-doesnt-work)
I made changes on the only eda_process.py however, there are other files that need to be fixed. 
If you agree with this change, then we can fix others as well. 
However, since the type check can be the same for all the files, we can write a function that we can call for all the files.
Please let me know what do you think?
Best regards,
Celal
Reset_index only when the input is series and has an index other than the default
As an example, I have made changes in eda_process.py
` 
if type(eda_signal) is pd.Series and type(eda_signal.index) != pd.RangeIndex:
eda_signal.reset_index(inplace=True, drop=True)
`
- [ X] I …
> input check for series when non-default index is set.

- neurokit2/ecg/ecg_simulate.py
Added argument to ecg_simualate to allow users to specify hr std when generating with ecgsyn method.
This PR aims to allow users to specify hr std to mimic the functionality of the original ecgsyn implementaiton.
I added the argument for hr std in the ecg_simulate function and kept 1 the default in the case that it is not specified.
> Add hrstd argument to ecg_simulate

- neurokit2/ecg/ecg_delineate.py
This PR fixes the changes made in 2fb051df12a29dd3e74c0a67a9d61c414254d007 which aimed to prevent an integer overflow in `_dwt_resample_points`. See #387.
`numpy.ndarray.astype` will still copy with `copy=False` if the `dtype` argument [requirement is not satisfied](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.astype.html). (Converting an int32 array to a int64 array always needs to copy.)
> Fix casting to np.int64

- neurokit2/ecg/ecg_delineate.py
This PR aims at fix _dwt_delineate_tp_onsets_offsets fucntion when the there is no candidate_offsets.
I changed the `_dwt_delineate_tp_onsets_offsets ()` function so that won't show error when len(candidate_offsets)==0
> fix error when len(candidate_offsets)==0

- neurokit2/ecg/ecg_delineate.py
This PR aims to fix a small bug in neurokit2/ecg/ecg_delineate.py which arises because the emptiness check of 'candidate_offsets' is performed using 'onset_slope_peaks' instead of 'offset_slope_peaks'. This PR prevents the function from erroneously passing the emptiness check and subsequently throwing an error when attempting to get 'candidate_offsets[0]'. 
The only proposed change is correcting line 368's 'onset_slope_peaks' reference to 'offset_slope_peaks'.
> [Fix] Fix offset bug in neurokit2/ecg/ecg_delineate.py

- neurokit2/signal/signal_fixpeaks.py
- tests/tests_signal_fixpeaks.py
Fixes neuropsychology/NeuroKit#378
This change stops the iteration in `_signal_fixpeaks_kubios` when the number of detected artifacts stops decreasing. This logic is guaranteed to stop as the number of artifacts can't drop below zero.
> Stop signal_fixpeaks iteration when number of artifacts stops decreasing

- neurokit2/ecg/ecg_delineate.py
- neurokit2/ecg/ecg_findpeaks.py
Throughout the package, signal_zerocrossings is used to find indices where signal crosses 0. Before calling signal_zerocrossings, signals are, correctly, checked to ensure that peaks[current_idx] is positive and peaks[next_idx] is negative. However, peaks[current_idx:next_idx] is used in the signal_zerocrossings call, excluding peaks[next_idx] value. When signal is positive until x[next_idx], the function currently throws error.
All signal_zerocrossings calls are changed so that the second peak is included in signal_zerocrossings calls. That is, peaks[current_idx:next_idx] becomes peaks[current_idx:next_idx+1] in all cases.
> [Fix] Fix signal_zerocrossings indexing issues

- neurokit2/ecg/ecg_findpeaks.py
- tests/tests_ecg_findpeaks_MWA.py
This optimization speeds up the moving average computation by an order of
magnitude. This is the most time-consuming part of pantompkins peak
detection, which after this optimization is about 5x faster on my computer.
Note the TODO about the _ecg_findpeaks_MWA output. I intentionally kept
this as a pure optimization with no impact on the output of the function,
but I do wonder whether the earlier implementation was actually incorrect,
or if the output is intentionally shifted by one.
> Optimize _ecg_findpeaks_MWA

- neurokit2/eda/eda_findpeaks.py
This is to fixed the issue number [#421](https://github.com/neuropsychology/NeuroKit/issues/421)
In eda_findpeaks.py, I replaced 
```python
scrs = np.array(scrs)
```
with
```python
scrs = np.array(scrs, dtype=object)
```
> Fixed issue #421:  ragged nested sequences

- neurokit2/ecg/ecg_findpeaks.py
Fix rare peak-inside-padding issues in _ecg_findpeaks_kalidas
I occasionally see failures in `kalidas2017` peak detection caused by the algorithm returning peak indices that exceed the length of the input signal.
The cause of this problem is the padding needed by the SWT computation, and the simple fix is to drop the padding after the SWT computation is done.
I can't share the data that triggers this problem, and I couldn't think of an easy way to generate an alternative test case. Thus unfortunately I don't have a test case to go with this change. At least the change itself is very simple, and I've verified it locally with the data I have.
> Fix rare peak-inside-padding issues in _ecg_findpeaks_kalidas

- README.rst
There is a tiny error in the examples in README of EOG.
A parameter lost in `eog_plot`.
The lost parameter is added.
`plot = nk.eog_plot(signals, sampling_rate=100)` to `plot = nk.eog_plot(signals, info, sampling_rate=100)`
> A parameter lost in `eog_plot`

- neurokit2/epochs/epochs_create.py
#459 brings to our attention a mistake in `epochs_create()`. The duration information from `events` was not transformed to the correct unit (from samples to seconds), resulting in wrong epochs being created. This PR aims to fix this issue
> fix epochs_end from duration of events

- NEWS.rst
- neurokit2/ecg/ecg_intervalrelated.py
- neurokit2/eda/eda_intervalrelated.py
- neurokit2/emg/emg_intervalrelated.py
- neurokit2/eog/eog_intervalrelated.py
- neurokit2/ppg/ppg_intervalrelated.py
- neurokit2/rsp/rsp_intervalrelated.py
- tests/tests_ecg.py
- tests/tests_eda.py
- tests/tests_emg.py
- tests/tests_eog.py
- tests/tests_rsp.py
The `*_intervalrelated()` functions can either take one whole dataframe as an input:
```
nk.ecg_intervalrelated(df, sampling_rate=100)
Out[506]: 
ECG_Rate_Mean  HRV_RMSSD  HRV_MeanNN  ...  HRV_RCMSE   HRV_DFA  HRV_CorrDim
0      86.392105  38.837766  694.756381  ...   1.666211  0.717625     1.294291
```
or a **dictionary of dataframes** like so
```
epochs = nk.epochs_create(df, events=[0, 15000], sampling_rate=100, epochs_end=150)
nk.ecg_intervalrelated(epochs)
Out[508]: 
ECG_Rate_Mean  HRV_RMSSD  ...  HRV_RCMSE   HRV_DFA  HRV_CorrDim
1    86.389814   3.638450  ...   1.456566  0.607610     1.383023
2    86.394396   4.032578  ...   1.834454  0.768419     1.264621
```
I think it's clearer if we append the label of the dataframe (extracted from the epochs input) to the final features output …
> Add labelling to subepochs

- NEWS.rst
- neurokit2/eeg/mne_data.py
Let users know to + have the option to specify `path` argument if the mne data folder is not present (where the data is then downloaded into this path) 
> Fix download error when downloading `mne` datasets

- NEWS.rst
- neurokit2/complexity/complexity_lempelziv.py
- neurokit2/complexity/complexity_optimize.py
- neurokit2/complexity/complexity_r.py
- neurokit2/complexity/entropy_approximate.py
- neurokit2/complexity/entropy_fuzzy.py
- neurokit2/complexity/entropy_multiscale.py
- neurokit2/complexity/entropy_sample.py
- neurokit2/complexity/entropy_shannon.py
- neurokit2/complexity/fractal_correlation.py
- neurokit2/complexity/fractal_dfa.py
- neurokit2/complexity/fractal_higuchi.py
- neurokit2/complexity/fractal_katz.py
- neurokit2/hrv/hrv_nonlinear.py
- neurokit2/rsp/rsp_rrv.py
- setup.py
- tests/tests_complexity.py
Return complexity indices in the form of tuples like so:
```
lzc, parameters = nk.complexity_lempelziv(signal, threshold="median")
```
where parameters is a dictionary. As part of https://github.com/neuropsychology/NeuroKit/projects/2#card-66890225
> Format `complexity` outputs

- NEWS.rst
- neurokit2/emg/emg_activation.py
> Sanitize emg offset indices

- neurokit2/signal/signal_fixpeaks.py
This PR aims at repairing a possible bug in the  _interpolate_big method from the signal_fixpeaks method, i.e. wrong argument is passed to the interpolate function.
One-line change which is self-explanatory.
- [ x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [ x] My PR is targetted at the **dev branch** (and not towards the master branch).
- [ x] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the errors.
- [ x] I have added the newly added features to **News.rst** (if applicable)
> [Fix] _interpolate_big method from signal_fixpeaks method

- neurokit2/signal/signal_fixpeaks.py
This PR aims at repairing a possible bug in the _signal_fixpeaks_neurokit method from the signal_fixpeaks method, i.e., the wrong argument is passed to the _interpolate_big function.
Another night - another catch! 
One-line change which is self-explanatory.
> [Fix] Signal_fixpeaks_neurokit

- NEWS.rst
- neurokit2/hrv/hrv_utils.py
Throw error in `_hrv_sanitize_input()` if intervals instead of peaks detected
> Distinguish intervals from peaks in `hrv_*()`

- neurokit2/rsp/rsp_eventrelated.py
- neurokit2/rsp/rsp_findpeaks.py
- neurokit2/rsp/rsp_fixpeaks.py
- neurokit2/rsp/rsp_peaks.py
- neurokit2/rsp/rsp_plot.py
- neurokit2/rsp/rsp_process.py
- neurokit2/rsp/rsp_rrv.py
See https://github.com/neuropsychology/NeuroKit/projects/4#card-67978636 and #528
> Add and clarify RSP features

- NEWS.rst
- neurokit2/eeg/__init__.py
- neurokit2/eeg/eeg_badchannels.py
- neurokit2/eeg/mne_channel_add.py
- neurokit2/eeg/mne_channel_extract.py
- neurokit2/eeg/mne_crop.py
- neurokit2/eeg/mne_to_df.py
- neurokit2/eog/__init__.py
- neurokit2/eog/eog_findpeaks.py
- neurokit2/eog/eog_peaks.py
- neurokit2/epochs/epochs_plot.py
`mne` raw objects have an attribute called `first_samp` corresponding to the time lapsed after the system start and before the start of the recording, and so the first event's sample number is always > 0. This is taken into account for in mne functions but not in neurokit yet 
See http://predictablynoisy.com/mne-python/generated/mne.io.RawArray.html
> Functions to account for more `mne` features

- neurokit2/hrv/hrv_time.py
Remove unused args in `_sdnni()` and `_sdann()`
As mentioned [here](https://github.com/neuropsychology/NeuroKit/pull/571#issuecomment-961596438), `sampling_rate` is not used in either functions. 
@DominiqueMakowski the multiplication by 1000 is to convert from seconds to milliseconds. Since window_size is in minute, there is no need to use `sampling_rate` in the conversion.
> Remove unused args in hrv_time

- README.rst
If we run the current example code for EMG in the Readme text, this will result in the below error.
I added an ending "s" to the signal, now it works fine!
> Error removed in the Readme EMG example part

- neurokit2/complexity/optim_complexity_tolerance.py
This PR aims to fix the selection of the optimal r value on `_optimize_tolerance_recurrence`.
On line 130, the `r_range` value closest to 0.05 was being used to select itself, when in fact it's the `recurrence_rate` value closest to 0.05 to be used to select the `r_range` value.
> Fix complexity_tolerance using recurrence method

- neurokit2/eda/eda_process.py
I do this PR just to eliminate the duplicity/typo of hardcoding the sanitization of the Series in the eda_process function.
I changed the `eda_process ()` function so that only calls `signal_sanitize()`, instead of calling and sanitize immediately afterwards.
> [Fix] Avoid duplicated input sanitization in eda_process

- neurokit2/hrv/hrv_frequency.py
got in a muddle with GitHub, but sorted that technical issue now. so good to go I think.
I have allowed for changes in frequency bands to propagate through.  Further improvements to this could be made if requested. Trying to be ultra careful.
I note on code check that "hrv_frequency.py:14:0: W9015: "kwargs" missing in parameter documentation (missing-param-doc)" but I think this is a pre-existing warning.
I changed the hrv_frequency function to propagate through the changes to frequency bandings. Also needs a line to correct the maximum_frequency to the top of the top (VLF) banding.
- [ x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIB …
> [Fix] hrv_frequency(): changes in frequency bands correctly propagate

- neurokit2/epochs/epochs_plot.py
This PR fixes a typo in the `epochs_plot()` function
Since the sampling rate of `bio_eventrelated_100hz` is 100, I think the sampling rate passed to `epochs_create()` should be 100 instead of 200.
> [Docs] fix typo (sampling rate) in epochs_plot example

- neurokit2/ecg/ecg_process.py
This PR fixes #602 . It makes such that the detected RPeaks get added to `ecg_quality`.
Runs in `docs/examples/bio_custom/bio_custom.ipynb`. May have to adapt tests.
- `rpeaks["ECG_R_Peaks"]` is used instead of `None` for `ecq_quality`.
- Some automatic formatting
> [Fix] Added detected rpeaks to ecg_process

- neurokit2/complexity/entropy_multiscale.py
- neurokit2/complexity/entropy_shannon.py
- neurokit2/complexity/fractal_correlation.py
- neurokit2/complexity/fractal_dfa.py
- neurokit2/hrv/hrv_frequency.py
- neurokit2/hrv/hrv_nonlinear.py
- neurokit2/hrv/hrv_time.py
~~Modify the `hrv_time()` function such that the documentation for `MedianNN` reflects what is actually computed and implement the previous description of MedianNN: The median of the absolute values of the successive differences between RR intervals.~~
I corrected some errors in the documentation of `hrv_time()`, `hrv_frequency()`, `hrv_nonlinear()`, `entropy_shannon()`, `entropy_multiscale()`, `fractal_correlation()`, and `fractal_dfa()`.
I changed the `hrv_time()` function as follows:
1. Changed documentation of `MedianNN` and `MCVNN`
~~2. Added `MedianSD` (wasn't sure about the name) as a feature: The median of the absolute values of the successive differences between RR intervals.~~
I also made small changes to the documentation of `hrv_frequency()`, `hrv_nonlinear()`, …
> [Docs] Fix documentation of various HRV features

- neurokit2/complexity/optim_complexity_dimension.py
This PR fixes a typo in the docstring of the function complexity_dimension(). The function should return the optimal embedding dimension and not the delay, as stated in the docstring.
- I changed the docstring (line 75).
- Some changes made by black formatter
> [Docs] Typo fix in complexity_dimension() docstring

- neurokit2/complexity/entropy_multiscale.py
Default dimension parameters for entropy functions should be 3 as discussed in #714 
- Changed the default behaviour in `entropy_multiscale()` function for the dimension parameter from 2 to 3.
- Minor formatting and code style changes.
Should this be included in **News.rst**?
Is `entropy_multiscale()` used else where? Or should the parameter be updated elsewhere?
> [Breaking] entropy_multiscale(): default dimension is now 3 instead of 2

- neurokit2/hrv/hrv_frequency.py
- neurokit2/hrv/intervals_preprocess.py
- neurokit2/hrv/intervals_process.py
- neurokit2/hrv/intervals_utils.py
- neurokit2/signal/signal_psd.py
This PR aims to add the ability to use the lombscargle PSD method without interpolating the signal, i.e., so that (possibly unevenly spaced) timestamps can be directly used. See also  https://github.com/neuropsychology/NeuroKit/issues/671#issuecomment-1192153962
1. I changed the `hrv_frequency()` function so that the timestamps `t` are passed as an argument to `signal_psd()` if the `interpolation_rate` argument is set to `None`
2. I added the timestamps `t` as an argument to `signal_psd()` so they can be passed to `_signal_psd_lomb()`
3. I added functions to check whether the timestamps were already interpolated to be evenly spaced (`_intervals_time_uniform()`) and if so, determine their sampling rate (`_intervals_time_to_sampling_rate()`), so that the user can pass interpolated R-R …
> [Feature] use lombscargle PSD method without interpolation

- docs/functions/ecg.rst
- neurokit2/ecg/__init__.py
- neurokit2/ecg/ecg_invert.py
- neurokit2/ecg/ecg_peaks.py
- neurokit2/ecg/ecg_quality.py
- tests/tests_ecg.py
This PR aims at adding the ability to identify and correct ECG signal inversion. See also https://github.com/neuropsychology/NeuroKit/issues/558
I added the `ecg_invert()` function so that a user could optionally correct for signal inversion in the raw ECG data before using the other processing functions (cleaning, peak detection).
> [Feature] ECG inversion

- neurokit2/hrv/hrv.py
- neurokit2/hrv/hrv_frequency.py
- neurokit2/hrv/hrv_nonlinear.py
- neurokit2/hrv/hrv_rqa.py
- neurokit2/hrv/hrv_rsa.py
- neurokit2/hrv/hrv_time.py
- neurokit2/hrv/hrv_utils.py
- neurokit2/hrv/intervals_process.py
- neurokit2/hrv/intervals_to_peaks.py
- neurokit2/hrv/intervals_utils.py
- tests/tests_hrv.py
This PR aims at adding the ability to perform HRV analysis in the case of missing interbeat intervals. See also https://github.com/neuropsychology/NeuroKit/issues/541
I changed the `hrv_time()` and `hrv_nonlinear()` functions so that for some features, differences between intervals that are not actually successive are removed and the timestamps of the intervals are taken into account. 
(Maybe this checklist should be updated to remove the code checks & News.rst points? https://github.com/neuropsychology/NeuroKit/issues/692#issuecomment-1211437961)
> [Feature] adjust HRV functions for missing intervals

- neurokit2/ecg/ecg_delineate.py
- neurokit2/signal/signal_formatpeaks.py
This PR aims to fix an error in `ecg_delineate()` where invalid indices were returned. See also https://github.com/neuropsychology/NeuroKit/issues/729
I changed the `ecg_delineate()` function so that within `_ecg_delineator_peak()`, all indices of fiducial points are checked to ensure that they are not larger than the number of samples in the ECG signal - 1
> [Fix] ECG delineator peak index

- neurokit2/hrv/intervals_utils.py
- tests/tests_hrv.py
This PR aims to fix a mistake I made in https://github.com/neuropsychology/NeuroKit/pull/720 that prevented the detection of missing data with the timestamps of interbeat intervals (sorry I just noticed)
I changed the `_intervals_missing()` function so that it returns `True` if the following 3 conditions are satisfied:
1. At least one of the interbeat intervals **doesn't** correspond to the difference between the timestamps provided 
2. At least one of the interbeat intervals **does** correspond to the difference between the timestamps provided 
3. The intervals are not detected to be interpolated
I also added a test `test_hrv_missing()` to confirm that providing the timestamps corresponding to the interbeat intervals improves the estimation of RMSSD with missing data.
> [Fix] Detection of missing interbeat intervals

- neurokit2/data/__init__.py
- neurokit2/data/read_video.py
Sometimes easy things are complicated in Python.
> [Feature] read_video() function read video files into array (mp4)

- docs/functions/data.rst
- docs/functions/index.rst
- docs/functions/misc.rst
- docs/functions/video.rst
- neurokit2/__init__.py
- neurokit2/data/read_bitalino.py
- neurokit2/data/read_video.py
- neurokit2/misc/__init__.py
- neurokit2/misc/progress_bar.py
- neurokit2/ppg/ppg_report.py
- neurokit2/signal/signal_interpolate.py
- neurokit2/signal/signal_rate.py
- neurokit2/video/__init__.py
- neurokit2/video/video_blinks.py
- neurokit2/video/video_face.py
- neurokit2/video/video_plot.py
- neurokit2/video/video_ppg.py
- neurokit2/video/video_skin.py
Perhaps for 2.3
Can now easily plots some frames alongside physio signal(s); will be useful for debugging and validating
> [Feature] Webcam video processing for remote physiology (rPPG, ...) (EXPLORATORY)

- neurokit2/signal/signal_detrend.py
- studies/ecg_benchmark/README.md
- studies/ecg_benchmark/make_data.py
New PR as a follow-up of the discussion here https://github.com/neuropsychology/NeuroKit/pull/734
> [docs] window size for locreg detrending

- neurokit2/hrv/hrv_rsa.py
Convert RSA P2T output in ms
In the description it says it should return ms but it was in second i've fixed it as discussed in [here](https://github.com/neuropsychology/NeuroKit/discussions/763)
I've also reworked the p2t to compute the variation between the max RRI in exh and the min RRI in inh following the [paper](https://pubmed.ncbi.nlm.nih.gov/2100356/) from Grossman 1990  
This is a working version (on the data i've tested at least )  but should just be a starting point since it's not really validated i hope it can be helpful :) 
- modified the _hrv_rsa_p2t function multiplying by 1000 the difference in TF after it has been divided by the sampling rate
- added cycle inh and exh separately to compute minima
- added buffer of 750 ms to the peak and end cycle in order to take into …
> Fix ms hrv rsa + proposed fix for RSA P2T

- docs/conf.py
This PR aims to add a creative commons license to documentation (as discussed in #769 ).
I changed the `conf.py` file by appending some text to the 'author' field. The text states the license for the documentation.
The current commit uses the [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) license, which is the license commonly used in open access publications. The license does require the user to attribute the original source. It allows the authors to retain the copyright.
An alternative, more permissive license is the [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/) license, which places work "as completely as possible in the public domain". This would remove the need for users to attribute the original documentation, and would also mean that the authors …
> Added creative commons license to documentation

- neurokit2/ecg/ecg_delineate.py
- neurokit2/ecg/ecg_segment.py
This prevents indices larger than the ECG signal indices from being returned by `ecg_delineate()`. See https://github.com/neuropsychology/NeuroKit/issues/772
I changed `ecg_delineate()` so that regardless of which delineation method is used, the output is postprocessed such that any indices that are larger than the ECG signal indices are removed (originally this postprocessing was only done in `_ecg_delineator_peak()`.
I also changed `ecg_segment()` so that the final heartbeat segment only contains points from the original ECG signal (not zeros appended at the end), since that caused invalid indices to be detected within `ecg_delineate()`. But I can revert this change or make it an optional argument, as invalid indices will be removed in `ecg_delineate()` anyway.
Here are some things to …
> [Fix] invalid indices in ecg_delineate

- neurokit2/rsp/rsp_amplitude.py
- neurokit2/rsp/rsp_findpeaks.py
`rsp_amplitude()` expects there to be the same number of peaks and troughs, so I modified the `scipy` method of finding peaks in a respiration signal so that the output is sanitized such that there are the same number of peaks and troughs.
1. I modified `_rsp_findpeaks_scipy()` to use `_rsp_findpeaks_sanitize()`
> [Fix] sanitize RSP extrema found by scipy method

- neurokit2/signal/signal_interpolate.py
Interpolating a single value currently raises an error, causing tests [here](https://github.com/neuropsychology/NeuroKit/pull/785) to fail, and I know this has also previously been an issue https://github.com/neuropsychology/NeuroKit/issues/740
I changed the `signal_interpolate()` function so that it returns a constant signal if only one x value is provided rather than raising an error. 
We could alternatively check the length of the input to `signal_interpolate()` in `rsp_rvt()` where it is currently causing the error. But unless we can think of a situation in which a constant signal is not the desired output given only one x value, I feel like directly modifying `signal_interpolate()` makes more sense than checking the length of the input wherever `signal_interpolate()` is used? 
Here …
> [Fix] interpolate signal with only one value 

- neurokit2/ppg/ppg_process.py
- neurokit2/rsp/rsp_methods.py
- neurokit2/rsp/rsp_process.py
I noticed that `rsp_methods()` uses the default arguments of `rsp_findpeaks()` instead of `rsp_peaks()`. `rsp_peaks()` is the function used in `rsp_process()` so I think we should use that. I also noticed that I left the plots generated in the report static here https://github.com/neuropsychology/NeuroKit/pull/785, so I fixed that. 
1. I changed the `rsp_methods()` function to use `rsp_peaks()`
2. I changed the `rsp_process()` and `ppg_process()` functions to generate reports with interactive plots
> [Fix] Function used in rsp_methods

- neurokit2/hrv/hrv_frequency.py
- neurokit2/signal/signal_psd.py
This PR aims to fix https://github.com/neuropsychology/NeuroKit/issues/799 to plot frequency-domain HRV analysis with the `lombscargle` PSD method given unevenly spaced data 
1. I changed the `_hrv_frequency_show()` and `signal_psd()` so that when `sampling_rate=None`, the sampling rate is estimated using the median difference between timestamps 
_side note: this choice was somewhat arbitrary, I could have also used the mean or mode difference, I thought about adding a function along the lines of `_estimate_sampling_rate(t, method="mode")`, but wasn't sure where to put it_
> [Fix] frequency-domain HRV with lombscargle given unevenly spaced data

- neurokit2/signal/signal_interpolate.py
This PR aims to prevent the following warning when running `signal_interpolate()`:
`DeprecationWarning: elementwise comparison failed; this will raise an error in the future.`
I changed the `signal_interpolate()` function so that a line (that I think I added, by the way, sorry) using `np.all` now uses `np.array_equal` instead: 
https://stackoverflow.com/questions/44574679/python-deprecationwarning-elementwise-comparison-failed-this-will-raise-an
> [Fix] prevent deprecation warning in signal_interpolate()

- neurokit2/ppg/ppg_intervalrelated.py
- neurokit2/rsp/rsp_intervalrelated.py
- neurokit2/signal/signal_plot.py
- tests/tests_eda.py
Removes a failing test comparing an EDA method with the biosppy package. See https://github.com/neuropsychology/NeuroKit/issues/824 
I changed the `test_eda_peaks()` function so that the `kim2004` method is not compared with biosppy.
> [Fix] remove eda biosppy test

- neurokit2/ppg/ppg_findpeaks.py
- tests/tests_ppg.py
This PR aims at fixing an issue with the output format of PPG peaks returned with the bishop method. See also https://github.com/neuropsychology/NeuroKit/issues/831
As suggested by @Ian-Ren (thank you!) I changed the `ppg_findpeaks()` function so that only one dimension is returned. 
I also modified the `test_ppg_report()` function so that the bishop method is tested, to confirm that this change does make the output format correct.
> [Fix] bishop peaks format

- neurokit2/complexity/complexity.py
- neurokit2/complexity/fractal_tmf.py
- neurokit2/complexity/optim_complexity_tolerance.py
- neurokit2/eeg/mne_channel_extract.py
- neurokit2/hrv/hrv_nonlinear.py
- neurokit2/hrv/intervals_process.py
- neurokit2/ppg/ppg_intervalrelated.py
- neurokit2/rsp/rsp_process.py
- neurokit2/signal/signal_plot.py
Seems I forgot to include all the outputs in the docstring for `intervals_process()`.
I added interpolation_rate to the docstring of the `intervals_process()` function so that it reflects what the function does.
update: I also made some changes to address some of the warnings in the documentation check
> [Docs] various docs fixes

- neurokit2/ppg/ppg_simulate.py
- neurokit2/signal/signal_interpolate.py
- tests/tests_ppg.py
This PR aims at fixing an error that occurs with `ppg_simulate()` for some parameters (I think smaller sample rates causing duplicate x values corresponding to fiducial points). See also https://github.com/neuropsychology/NeuroKit/issues/832
1. I changed the `ppg_simulate()` function so that it uses `signal_interpolate()`
2. I changed `signal_interpolate()` so that it can process duplicate x values
3. I added the `"akima"` method to `signal_interpolate()`.
4. I added a test case to `test_ppg_simulate()` that was failing in the previous version (longer duration, lower sample rate) to demonstrate how the changes fix the error
> [Fix] interpolation error when simulating PPG data

- neurokit2/ppg/ppg_intervalrelated.py
- tests/tests_ppg.py
Hello,
while writing some custom code for nk2, I tried gating the calculation of the time-based, frequency-based and non-linear PPG HRV Parameters. While doing that I noticed that, when running the code with all three types of HRV parameters it worked flawlessly - as it is intended using ppg_analyze.
But setting any of the gates to false, did not work, if they have been true before without restarting the kernel. Looking into the issue by extensive testing, I found the following:
In both functions (`_ppg_intervalrelated_hrv(...)` and `_ppg_intervalrelated_formatinput(...)`), the return variable is also in the arguments list for the functions (i.e. `output`):
```
def _ppg_intervalrelated_hrv(data,
sampling_rate,
output={},
):    
colnames = data.columns.values
if len([i for i in colnames if …
```
> [Fix] Fixed memory baviour in hrv calc

- neurokit2/ecg/ecg_quality.py
from Zhao and Zhang's paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6011094/#B11) in figure 11
the the basSQI should be (1-∫p(t)) / ∫p(t). I therefore changed the _ecg_quality_basSQI function return from "return (1 - num_power) / dem_power" to  "return (1 - num_power) / dem_power"
> ECG: Corrected Error in basSQI calculation

- neurokit2/signal/signal_filter.py
- tests/tests_signal.py
As a step towards better handling of missing data (see https://github.com/neuropsychology/NeuroKit/issues/838), this PR aims to allow for filtering signals even if they contain NaNs.
1. I changed the `signal_filter()` function so that NaNs are interpolated before filtering and then added back after filtering.
2. I added `test_signal_filter_with_missing()` to test that the signal containing NaNs is filtered.
> [Feature] filter signals with missing data

- neurokit2/eda/eda_process.py
This PR fixes a typo in the `eda_process()` docstring mentioned in https://github.com/neuropsychology/NeuroKit/issues/851
> [Fix] typo docstring eda process

- neurokit2/emg/emg_clean.py
- neurokit2/emg/emg_methods.py
- neurokit2/emg/emg_plot.py
- neurokit2/emg/emg_process.py
- neurokit2/misc/report.py
- neurokit2/ppg/ppg_clean.py
- neurokit2/ppg/ppg_methods.py
- neurokit2/ppg/ppg_process.py
- neurokit2/rsp/rsp_methods.py
- tests/tests_emg.py
This PR aims to generate an interactive HTML report describing EMG processing as described in https://github.com/neuropsychology/NeuroKit/issues/665
1. I changed the `emg_plot()` function so that it optionally generates an interactive plot with plotly
2. I added an `emg_methods()` function
3. I changed the `emg_process()` function so that it optionally generates a report
4. I wrote a test for generating a report
5. I modified the docstring in `report.py` to reference EMG; however, I did not add any EMG-specific logic for generating a summary table. I wonder if we should use `bio_analyze()` to generate the table rather than checking the column names within `report.py`
> [Feature] EMG report

- neurokit2/ecg/ecg_clean.py
- neurokit2/events/events_find.py
- tests/tests_ecg.py
The ECG preprocessing method got recently updated (https://github.com/scientisst/BioSPPy/pull/12), so we should update accordingly (especially since the updated version seems objectively better than the old one that was too abrasive).
> [Breaking] ecg_clean(): update biosppy method

- neurokit2/complexity/utils.py
- tests/tests_complexity.py
This PR aims to fix failing tests related to `sklearn.neighbors.KDTree.valid_metrics`. See also: https://github.com/neuropsychology/NeuroKit/pull/814#issuecomment-1619216245
I changed the `valid_metrics` to `valid_metrics()` in `complexity.utils()` according to current documentation: https://scikit-learn.org/stable/modules/generated/sklearn.neighbors.KDTree.html
> [Fix] version sklearn valid_metrics

- neurokit2/hrv/hrv_time.py
- neurokit2/signal/signal_period.py
SDNN / RMSSD  is ***supposedly*** a time-domain equivalent for the low Frequency-to-High Frequency(LF/HF) Ratio ([Sollers et al., 2007](https://www.researchgate.net/publication/6344500_Comparison_of_the_ratio_of_the_standard_deviation_of_the_R-R_interval_and_the_root_mean_squared_successive_differences_SDrMSSD_to_the_low_frequency-to-high_frequency_LFHF_ratio_in_a_patient_population)).
> [Feature] HRV: Add SD/RMSSD index (Sollers, 2007)

- neurokit2/epochs/eventrelated_utils.py
Fixes https://github.com/neuropsychology/NeuroKit/issues/867
`_eventrelated_addinfo` in _epochs/eventrelated_utils.py_ has these lines:
```python
if "Index" in epoch.columns:
output["Event_Onset"] = epoch.loc[np.min(np.abs(epoch.index))]["Index"]
```
`np.min(np.abs(...))` returns the smallest absolute time offset in seconds. If the smallest absolute value is of a negative time offset, then it produces a non-existent index, causing an error when indexing in epoch.loc.
This commit replaces it with `iloc[np.argmin(np.abs(...))]`, indexing by integer index.
> [FIX] KeyError in _eventrelated_addinfo

- neurokit2/ecg/ecg_process.py
This PR aims at updating and improving the documentation and code readability of the ecg_process() function.
This PR does not change any external behaviour of the function. Just refactoring and documentation.
> [Docs] ecg_process: improve documentation and readability

- neurokit2/complexity/utils_complexity_symbolize.py
This PR aims to allow for setting the random seed in `complexity_symbolize()`. See also https://github.com/neuropsychology/NeuroKit/issues/879
I added a `random_state` argument to the `complexity_symbolize()` function so that the seed is passed to `scipy.cluster.vq.kmeans2()`
> [Feature] add random_state to complexity_symbolize

- neurokit2/bio/bio_process.py
- neurokit2/data/__init__.py
- neurokit2/data/read_bitalino.py
- neurokit2/data/read_xdf.py
Note to those using the *Muse* EEG headband with LSL, if you want to synchronize it with LSL you'll need this branch: https://github.com/alexandrebarachant/muse-lsl/pull/197
> [Feature] read_xdf() - easily read and tidy up signals from Lab Streaming Layer (LSL) into a DataFrame

- README.rst
Fixed minor grammatical + punctuation errors.
Some grammatical + punctuation errors in README.rst:
- the singular-plural form of the verb in the present tense
- comma before and
- a singular-plural form of the noun
> [Docs] Minor Update README.rst

- data/fantasia/download_fantasia.py
- data/lemon/download_lemon.py
- data/ludb/download_ludb.py
- data/mit_arrhythmia/download_mit_arrhythmia.py
- neurokit2/data/__init__.py
- neurokit2/data/data.py
- neurokit2/data/database.py
This PR aims to allow for zip files to be automatically downloaded and extracted, as a first step towards automating the downloading and formatting of various datasets (see https://github.com/Tam-Pham/HRVStructure/issues/2#issuecomment-1656098785)
I added a `download_zip()` function to a `database.py` file (was thinking that this could be where the refactored functions for downloading individual databases could be moved to within NeuroKit), and I used this function for the fantasia and mit arrhythmia databases.
Let me know if you want me to change the naming (wasn't sure about `database.py`), and also if you have any thoughts on whether there should be automated tests for this (not sure if downloading entire datasets is a good idea with GitHub Actions)
> [Feature] download zip

- .github/workflows/tests.yml
- neurokit2/rsp/__init__.py
- neurokit2/rsp/rsp_intervalrelated.py
- neurokit2/rsp/rsp_rav.py
- tests/tests_rsp.py
#853 
I'm not aware of much literature on that, but it doesn't seem absurd as a potential feature of interest
> [Feature] Respiratory Amplitude Variability (RAV)

- docs/functions/ppg.rst
- neurokit2/ecg/ecg_peaks.py
- neurokit2/ecg/ecg_plot.py
- neurokit2/ecg/ecg_segment.py
- neurokit2/hrv/hrv_rsa.py
- neurokit2/ppg/__init__.py
- neurokit2/ppg/ppg_findpeaks.py
- neurokit2/ppg/ppg_peaks.py
- neurokit2/ppg/ppg_plot.py
- neurokit2/ppg/ppg_process.py
- neurokit2/ppg/ppg_segment.py
- neurokit2/signal/signal_rate.py
- tests/tests_bio.py
- tests/tests_ecg.py
- tests/tests_eda.py
- `ecg_plot()` and `ppg_plot()` now *require* the sampling_rate to be passed (for segmentation to happen) - also simplifies the code.
> [Feature] PPG plots improvements

- docs/examples/bio_custom/bio_custom.ipynb
- docs/examples/bio_intervalrelated/bio_intervalrelated.ipynb
- neurokit2/ecg/ecg_peaks.py
- neurokit2/ecg/ecg_plot.py
- neurokit2/ecg/ecg_segment.py
- neurokit2/ppg/ppg_peaks.py
- neurokit2/ppg/ppg_plot.py
- neurokit2/ppg/ppg_segment.py
- tests/tests_ecg.py
- tests/tests_ppg.py
- tests/tests_rsp.py
> [Feature] ppg_peaks() now has artifact correction

- .github/PULL_REQUEST_TEMPLATE.md
- neurokit2/complexity/entropy_shannon.py
- neurokit2/ecg/ecg_delineate.py
- neurokit2/hrv/hrv_nonlinear.py
I fixed some typos in `PULL_REQUEST_TEMPLATE.md`, `entropy_shannon()`, and `hrv_nonlinear()`.
Edit: I have also attempted to address a FutureWarning raised in the docs check by ecg_delineate
Edit x2: This attempt failed (see https://github.com/neuropsychology/NeuroKit/issues/897) so nevermind, let's just merge the typo changes
> [Docs] typos

- docs/functions/ppg.rst
- docs/functions/rsp.rst
- docs/functions/signal.rst
- neurokit2/complexity/entropy_spectral.py
- neurokit2/complexity/fractal_psdslope.py
- neurokit2/ecg/ecg_delineate.py
- neurokit2/ecg/ecg_phase.py
- neurokit2/ecg/ecg_quality.py
- neurokit2/emg/emg_activation.py
- neurokit2/emg/emg_plot.py
- neurokit2/misc/progress_bar.py
- neurokit2/rsp/rsp_phase.py
- neurokit2/rsp/rsp_plot.py
- neurokit2/signal/signal_binarize.py
- neurokit2/signal/signal_fillmissing.py
- neurokit2/stats/standardize.py
This PR aims to address a warning in the docs check caused by `ecg_delineate()`.
See https://github.com/neuropsychology/NeuroKit/issues/897#issuecomment-1709647506
> [Fix] docs build warning

- neurokit2/eda/eda_plot.py
Fix a bug where you had an exception if there was not the same number of peaks and onsets (issue #632). This can happen on signal that has been cut (ex: depending on difference conditions). 
The fix just ignores the first peak (only for display) when there is no onset for the first peak.
> [Fix] eda_plot throws ValueError when the number of onsets is not the same as the number of peaks

- neurokit2/complexity/complexity_decorrelation.py
- neurokit2/complexity/complexity_lyapunov.py
- neurokit2/ecg/ecg_plot.py
- neurokit2/signal/signal_autocor.py
- tests/tests_complexity.py
> [Feature] complexity_lyapunov(): more efficient method to compute LLE

- neurokit2/complexity/utils.py
This PR aims to fix the sklearn.neighbors.KDTree.valid_metrics() sanity check which has been introduced in skearn.__version__ 1.3.0 (and also in 1.3.0rc1), but has afterward been reverted due to compatibility issues with other libraries. More about this can be found here:
https://github.com/scikit-learn/scikit-learn/issues/26742
https://github.com/scikit-learn/scikit-learn/pull/26754
I changed the `if sklearn_version >= version.parse("1.3.0"):` condition to `if sklearn_version in [version.parse("1.3.0"), version.parse("1.3.0rc1")]:` so we can only cover the two cases in which `sklearn.neighbors.KDTree.valid_metrics` is not an attribute and is instead a method.
> fixed sklearn sanity checks for valid_metrics

- MANIFEST.in
when install neurokit2 by pip, tests folder in neurokit repository are installed in python env. they can conflict with other local tests directory.
This PR removed tests folder from setup.py by editing MANIFEST.in
> Remove tests from pyproject

- neurokit2/ecg/ecg_findpeaks.py
Optimize _ecg_findpeaks_elgendi in those areas of the code:
1. `blocks` could be just a bool array
2. Detection of start/end of block by only comparing `prev` vs `cur` (`blocks[i-1]`, `blocks[i]`) value. (about 2x faster) (even better when combined with *"1"*)
3. Use `enumerate(zip(...))` for iterating the array, (gives a small performance -but measurable- improvement)
4. Move some thresholds outisde of the loop, not to get calculated at each iteration
> [Improvement] Faster _ecg_findpeaks_elgendi

- neurokit2/ecg/ecg_findpeaks.py
This PR aims at fixing a bug where 'Nd' variable in _ecg_findpeaks_rodrigues was set to 0 in case of sampling_rate too small, effectively nulling the ECG first derivative
I have set N to be at least 2, so that Nd is at least 1.
> [Fix] Fixed rodrigues2021 ECG peaks detector (make it work with < 50Hz sampling rate)

- neurokit2/rsp/rsp_clean.py
- neurokit2/rsp/rsp_methods.py
See https://github.com/neuropsychology/NeuroKit/issues/950#issuecomment-1898404338.
1. I changed the docstring of the `rsp_clean()` function so that it describes the filter used.
2. I changed `rsp_methods()` so that the information for the processing report also describes the filter used.
> [Docs] update docs to reflect implementation of respiration signal cleaning with khodadad2018

- neurokit2/ecg/ecg_findpeaks.py
This PR aims to improve performanc of  `_ecg_findpeaks_hamilton` and fix some probable bugs
1. Changed possible bug popping from `n_pks` if `len(n_pks) > 8`, it should probably be `len(n_pks)`
2. Removed dead code of `i += 1` at the end of the loop
1. changed loop iteration range to avoid checks inside the loop
2. use `insort` instead of appending& sorting in an already sorted array (tested about x300-500 times faster on arrays of 50 elements)
3. Use deques instead of manually pushing and popping to reduce constantly allocating new memory.
> [Fix + Improvement] Faster _ecg_findpeaks_hamilton and bug-fix

- neurokit2/rsp/rsp_rate.py
Line 128 uses step size of 0.25/50, but line 137 uses 0.25/60
I think this is a typo, but please close if I'm wrong!
> [FIX] rr xcorr arange steps don't match

- neurokit2/__init__.py
- neurokit2/complexity/utils_complexity_symbolize.py
- neurokit2/emg/emg_activation.py
- neurokit2/signal/signal_resample.py
This PR aims to fix the failed documentation build check: https://github.com/neuropsychology/NeuroKit/actions/runs/8094952153/job/22120703414
I changed the `emg_activation()` function to index a DataFrame with `.loc`
> [Fix] build docs warning

- neurokit2/eda/eda_phasic.py
- pyproject.toml
- tests/tests_eda.py
The sparsEDA algorithm detects the tonic component in EDA and returns: a `driver`, `SCL` (tonic component), and `MSE` (residual). This is incompable with `eda_phasic()` which expects a `(tonic,phasic)` pair, see also Issue https://github.com/neuropsychology/NeuroKit/issues/964 .
This PR resolves Issue https://github.com/neuropsychology/NeuroKit/issues/964 by making `_eda_phasic_sparsEDA()` return a `(tonic,phasic)` pair where `tonic` is `SCL` and `phasic` is the difference between the original signal and the tonic component detected by sparsEDA,
> sparsEDA integration

- neurokit2/eda/eda_analyze.py
Small fix for the eda_analyze method to hand over the correct sampling rate to the eda_intervalrelated method. This PR addresses Issue #972.
Added sampling_rate=sampling_rate to eda_intervalrelated.
> [Fix] adding sampling rate parameter to eda_intervalrelated method

- neurokit2/data/read_acqknowledge.py
This PR aims at fixing the read_acqknowledge file which skipped duplicated channel names (e.g., Digital input channels)
I changed the read_acqknowledge in such a way where instead of iterating through the named_channels, it now iterates through the list of channels (by index) and add the channel.name to a counter. If there is a duplicate, the channel name now adds a number e.g., (1) to the end of the channel name if the channel has already been added.
Before:
```Python
print(data.columns)
Index(['PPG, Y, PPGED-R', 'RSP, Y, RSPEC-R', 'EMG A, Y, EMG2-R',
'SKT A, Y, SKT2-R', 'SKT B, X, SKT2-R', 'ECG, X, RSPEC-R',
'EMG B, X, EMG2-R', 'EDA, X, PPGED-R', 'Digital input'],
dtype='object')
```
After:
```Python
print(data.columns)
Index(['PPG, Y, PPGED-R', 'RSP, Y, RSPEC-R', 'EMG A, Y, EMG2-R', …
```
> [Fix] read_acqknowledge now also imports duplicated channel names

- docs/conf.py
- neurokit2/complexity/entropy_phase.py
- neurokit2/events/events_plot.py
- neurokit2/hrv/hrv_nonlinear.py
- neurokit2/microstates/microstates_plot.py
- neurokit2/signal/signal_power.py
This PR aims to address failing checks such as https://github.com/neuropsychology/NeuroKit/actions/runs/9143576310/job/25140400276?pr=987 that seem to be caused by the current version of `matplotlib` being incompatible with the `matplotlib.cm.get_cmap` syntax.
I changed all instances of `matplotlib.cm.get_cmap()` to `plt.get_cmap()`
> [Fix] Syntax to get colormap

- neurokit2/misc/report.py
- neurokit2/ppg/__init__.py
- neurokit2/ppg/ppg_methods.py
- neurokit2/ppg/ppg_peaks.py
- neurokit2/ppg/ppg_plot.py
- neurokit2/ppg/ppg_process.py
- neurokit2/ppg/ppg_quality.py
This PR aims at adding a new feature: PPG quality assessment. PPG quality assessment functionality has been added, and two initial quality assessment techniques have been included.
- Added ppg_quality.py
- Adjusted ppg_process.py to include quality assessment in the default processing pipeline
- Added details of the PPG quality assessment methods to ppg_methods.py
> [feature] added PPG quality assessment functionality

- neurokit2/ecg/ecg_quality.py
This PR aims at fixing the location of a misplaced double quote in the docstring of ecg_quality.py. This would be my first open source contribution :)
> [Docs] fix location of misplaced double quotes in docstring of ecg_quality.py

- neurokit2/signal/signal_filter.py
In order to avoid the DeprecationWarning thrown by NumPy (`DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)`) , the `freq` variable should be returned as a scalar and not as a list 
Change the `freqs` variable from list to a scalar when filter is either `lowpass` or `highpass`
> return frequency in `signal.signal_filter._signal_filter_sanitize` as scalar

- .github/workflows/docs-build.yml
The example images were not working for a while on the documentation website and I was curious as to what was wrong. It turns out that ipython at some point made the pickleshare dependency optional which meant that it was not automatically installed in the doc building workflow. I found the solution here on this issue ipython/ipython#14367. The solution is either to add pickleshare as a dependency or to update IPython. In this pull request I have simply gone with adding pickleshare as a dependency to get the images back online asap. Updating the remaining dependencies would be a topic for a different thread.
This PR fixes the issue #999 and allows users to be able to see the examples again on the documentation website. Here is the example from the issue with the actual image to see the …
> [Fix] Documentation Image Dependency

- neurokit2/ecg/ecg_findpeaks.py
- tests/tests_ecg_findpeaks.py
In working on #1007 I added logic to ensure that the find_peaks functions all worked when there were no peaks detected. We couldn't work on `_ecg_findpeaks_visibilitygraph` because ts2vg was broken in CI. Well https://github.com/CarlosBergillos/ts2vg/issues/36 (#1009 here) is fixed now and a new version is on pypi. This PR finishes what #1007 started. 
I added flat signal checking to `_ecg_findpeaks_visibilitygraph` -- if the min/max of the signal is equal then return an empty array
> [Fix] findpeaks neurokit index error

- neurokit2/hrv/hrv_time.py
This PR aims to improve the definitions of pNN50 and pNN20, which currently describe these features as being the proportion of RR intervals greater than 50/20 ms, but I think we should specify that these features are based on the absolute difference between successive RR intervals (rather than the RR intervals themselves, which we would normally expect to be well above 50 ms).
I changed the docstring of the `hrv_time()` function so that it contains the following definition adapted from [Mietus et al. (2002)](https://doi.org/10.1136/heart.88.4.378): _The percentage of absolute differences in successive RR intervals greater than 20/50 ms_
I also added references to [Mietus et al. (2002)](https://doi.org/10.1136/heart.88.4.378) and [Bigger et al. …
> [Docs] Revise definition of pNN50 and pNN20

- data/gudb/download_gudb.py
This PR aims to improve consistency in the naming of the GUDB database for R-Peak annotations and raw ECG data. I think a difference in naming could be problematic when selecting subsets of data for benchmarking:
https://github.com/neuropsychology/NeuroKit/blob/d42a2306a68efb5f59e5a86b4fac95dc5ff5359b/neurokit2/benchmark/benchmark_ecg.py#L83-L85
I changed `download_gudb.py` so that the database name for R-peaks uses an underscore instead of parentheses:
https://github.com/neuropsychology/NeuroKit/blob/d42a2306a68efb5f59e5a86b4fac95dc5ff5359b/data/gudb/download_gudb.py#L44
Such that it matches the corresponding name for raw ECG data:
https://github.com/neuropsychology/NeuroKit/blob/d42a2306a68efb5f59e5a86b4fac95dc5ff5359b/data/gudb/download_gudb.py#L38
> [Fix] GUDB name consistency

- neurokit2/ppg/ppg_findpeaks.py
Added MSPTDfast algorithm (v.1.1) for PPG beat detection.
This PR aims at adding the MSPTDfast algorithm (v.1.1) for PPG beat detection. This algorithm is a python implementation of the Matlab algorithm available at: https://github.com/peterhcharlton/ppg-beats/blob/main/source/msptdfastv1_beat_detector.m .
I changed the `ppg_findpeaks()` function by adding this additional beat detection method.
> [Feature] PPG peak detection: Add MSPTDfast algorithm (Charlton et al., 2024)

- neurokit2/ecg/ecg_peaks.py
This PR provides a brief update to description of the 'neurokit' ecg_peaks method, to include the publication validating this algorithm.
I changed the comments in the `ecg_peaks.py` function to add details of [this publication](https://doi.org/10.21105/joss.02621) which benchmarks the 'neurokit' ECG peak detection method.
> [Docs] Add info about NK ECG peak detection method

- docs/codebook.rst
- docs/conf.py
- docs/directives/csv_codebook_directive.py
- docs/index.rst
- neurokit2/ecg/ecg_eventrelated.py
- neurokit2/ecg/ecg_intervalrelated.py
- neurokit2/ecg/ecg_process.py
- neurokit2/eda/eda_eventrelated.py
- neurokit2/eda/eda_intervalrelated.py
- neurokit2/eda/eda_process.py
- neurokit2/eda/eda_sympathetic.py
- neurokit2/emg/emg_eventrelated.py
- neurokit2/emg/emg_intervalrelated.py
- neurokit2/emg/emg_process.py
- neurokit2/eog/eog_eventrelated.py
- neurokit2/eog/eog_intervalrelated.py
- neurokit2/eog/eog_process.py
- neurokit2/hrv/hrv_frequency.py
- neurokit2/hrv/hrv_nonlinear.py
- neurokit2/hrv/hrv_rsa.py
- neurokit2/ppg/ppg_eventrelated.py
- neurokit2/ppg/ppg_intervalrelated.py
- neurokit2/ppg/ppg_process.py
- neurokit2/rsp/rsp_eventrelated.py
- neurokit2/rsp/rsp_intervalrelated.py
- neurokit2/rsp/rsp_process.py
- neurokit2/rsp/rsp_rrv.py
This PR aims at creating a general `Codebook` that has all variables that can be generated from the NeuroKit package. The idea of this feature stems from discussion #1012 from @HeatherUrry.
The addition of this feature would allow users to more easily see what variables are extractable from NeuroKit and is useful in other software programs.
This pull request should be considered more as a draft as some polishing would still be required.
For example:
* Not all variables are likely included yet
* The field descriptions are mainly all just copied and pasted from what was already there, maybe we can update them more ? (maybe out of scope of this PR?)
* The Codebook page should probably have a better description
* Currently, the new directive does not support following new lines if we are …
> [Feature] Codebook Generation from Documentation

- neurokit2/eda/eda_phasic.py
>`np.Inf` was removed in the NumPy 2.0 release. Use `np.inf` instead.
> [Fix] Prevent `sparseda` method from raising `AttributeError`

- docs/codebook.rst
The problem was definitely mine. I left a `color: white` tag in the css of the cells.
Remove the css tag
> Fix: Lightmode now shows text correctly for the codebook

- neurokit2/eda/eda_process.py
There was a human error in converting the docstrings in `eda_process.py` during the codebook conversion. SCR_RiseTime had the same description as SCR_Amplitude after the change. This PR reverts the description to what it was before.
This PR closes #1031 .
Fix a docstring mistake while migrating to the new standard.
Revert docstring value to what it was before.
> [docs] Fix the docstring in eda_process for SCR_RiseTime

- neurokit2/hrv/hrv_time.py
This PR aims at improving the docstring of `hrv_time` function. This PR should fix https://github.com/neuropsychology/NeuroKit/issues/1046. 
I added a note to the docstring stating that "Where applicable, the unit used for these metrics is the millisecond."
- [X ] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
- [X ] My PR is targeted at the **dev branch** (and not towards the master branch).
> [Docs] Add a note about the units used for the time-based HRV metrics.

- neurokit2/ecg/ecg_delineate.py
This PR adds the `prominence` delineator to the `ecg_delineate` method. The prominence delineator tries to achieve a robust and interpretable wave detection by building upon peak prominence and physiology-based search windows. [1]
[1] J. Emrich, A. Gargano, T. Koka and M. Muma, "Physiology-Informed ECG Delineation Based on Peak Prominence," 2024 32nd European Signal Processing Conference (EUSIPCO), Lyon, France, 2024, pp. 1402-1406, doi: 10.23919/EUSIPCO63174.2024.10715353.
> [Feature] Add new ECG delineator method: Peak-Prominence (Emrich et al., 2024)

- neurokit2/signal/signal_interpolate.py
- tests/tests_signal.py
Fixing issue #1025: Missing np.squeeze for `y_values` when it is pands.series
Converted `y_values` to numpy array and squeezing in `signal_interpolate`.
Merged isinstance calls to fix pylint R1701 error.
> [Fix] Squeeze y_values in signal_interpolate

- neurokit2/ppg/ppg_quality.py
This PR aims at adding this feature...
Addressing issue #1043
Standardizing the interpolation step of the ppg_quality pipeline.
Within ppg_quality, changed 'templatematch' implementation to use interpolation method 'previous' rather than 'quadratic'. This aligns it with the 'disimilarity' implementation and is a better representation of the beat-by-beat nature of the quality measure.
> [Change] Update ppg_quality.py to use consistent interpolation method ('previous')

- neurokit2/ecg/ecg_quality.py
Fix issue https://github.com/neuropsychology/NeuroKit/issues/1052: `ecg_quality` is unbounded because of quadratic interpolation.
change interpolation to `linear`
> [Change] ecg_quality interpolation from quadratic to "previous"

- neurokit2/data/database.py
Refer https://github.com/neuropsychology/NeuroKit/issues/1061 for details.
Modified `data/database.py` as follows to match urllib API. Outgoing changes are commented with a `#` in the snippet below.
```python
def download_from_url(url, destination_path=None):
--- SNIP ---
if response.status == 200:
with destination_path.open("wb") as file:
file.write(response.read())
return True
else:
return False
```
[x] I have read the [CONTRIBUTING](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#structure-and-code) file.
[x] My PR is targeted at the dev branch (and not towards the master branch).
[x] I ran the [CODE CHECKS](https://github.com/neuropsychology/NeuroKit/blob/master/.github/CONTRIBUTING.rst#run-code-checks) on the files I added or modified and fixed the …
> [Fix] update data/database.py to use urllib methods. fixes #1061

- neurokit2/ecg/ecg_simulate.py
- Changes due to removal of wavelets from scipy in 1.15
scipy no longer does wavelets and recommends to use PyWavelet and addresses the issue from https://github.com/neuropsychology/NeuroKit/pull/1022#issuecomment-2653884456 .
> [Update] changes scipy.signal.daub to PyWavelets format

- neurokit2/complexity/complexity_lempelziv.py
- neurokit2/complexity/entropy_permutation.py
Numpy no longer has np.math and recommends the built-in math. This change has been made for the entire repository where np.math existed.
> [Fix] Replaced np.math with built-in math

- neurokit2/hrv/hrv_nonlinear.py
This PR aims at fixing https://github.com/neuropsychology/NeuroKit/issues/1084 where if a signal has less than 12 rri, the short window for the HRV DFA computation fails. This pull suggests simply returning nan if we have less than 12 rri as the HRV DFA is not useful for short signals.
Please let me know what you think.
> [Fix] Disable HRV DFA computation on signals with less than 12 rri

- neurokit2/ecg/ecg_process.py
`ecg_clean()` accepts `powerline` as a kwarg, which gets passed down to `signal_filter()`.  However, the `ecg_process()` wrapper that calls `ecg_clean()` does not accept or pass kwargs, including `powerline`.
This patch is an extension of the work in Issue #610.  It enables passing kwargs to `ecg_clean()` from a higher level, namely `ecg_process()`.
> Pass kwargs from ecg_process to ecg_clean

- setup.py
This PR adds Pywavelets to required dependency list.
After the discussion in https://github.com/neuropsychology/NeuroKit/pull/1093, we agreed on adding Pywavelets to dependency list.
I also sets `PyWavelets>=1.4.0` because the function `pywt.frequency2scale()` (which is called in `signal/signal_timefrequency.py`) was added in this version.
- ~~[ ] I have added the newly added features to **News.rst** (not applicable)~~
> Add Pywavelets to dependencies

- neurokit2/rsp/rsp_amplitude.py
- tests/tests_rsp.py
closes #1101 
I changed the rsp_amplitude function to better deal with different data type accepted for `rsp_cleaned` parameters (see #1101) 
> Fix rsp_amplitude type error

- neurokit2/ppg/ppg_clean.py
- tests/tests_ppg.py
This PR aims to add a reference for the "elgendi" method used in "ppg_clean", as previously no reference was provided.
I changed `ppg_clean.py` to add a reference to the following article:
_M. Elgendi, I. Norton, M. Brearley, D. Abbott, and D. Schuurmans (2013). Systolic peak detection in acceleration photoplethysmograms measured from emergency responders in tropical conditions. PLoS ONE, 8(10), 1–11._
I made changes to the functions `ppg_clean()` and `_ppg_clean_elgendi()`.
I presume that this is the correct [reference](https://doi.org/10.1371/journal.pone.0076585) because:
1. this is the reference used in `ppg_peaks.py`; and
2. it reports a very similar filtering approach (also using a Butterworth filter of bandpass of 0.5-8Hz, although neurokit currently uses order 3, whereas the …
> Updated Elgendi reference in ppg_clean.py

- neurokit2/data/read_xdf.py
This PR adds new functionality to the `read_xdf` function, allowing it to read XDF files from URLs.
It also fixes some out of date documentation and types, and explicitly outlines the function's return types.
(Various formatting changes were caused by linting)
If `filename` is a URL, `read_xdf` will now read the file from the URL as a BytesIO stream and pass it to `load_xdf`.
References to the dict of data frames returned have been removed. This seems like an artifact of an older version of the function, as it now returns a merged df of all streams
The function parameters and return values now have type hints, which improves the dev experience in the code editor, specifically with `info`, which can now autocomplete its properties.
Here are some things to check before creating the PR. If …
> [Feature] Allow `read_xdf` to read from URLs, and some typing/documentation improvements

- docs/resources/resources.rst
This PR aims to fix some dead links as mentionned in #1108 .
Two links were dead :
- Neuroimaging tutorials and resources <https://.github.io/tutorials-and-resources/> is completly dead.
- Electroencephalogram (EEG) Recording Protocol (Farrens et al., 2019) <https://protocolexchange.researchsquare.com/article/pex-779/v2>_ links to https://www.protocols.io/ home's page.
The first one is the Github IO page of this repository I believe : https://github.com/DimitraMoraiti/tutorials-and-resources.
It has been moved to this repository : https://github.com/learn-neuroimaging/hitchhackers_guide_brain that links to this page : https://learn-neuroimaging.github.io/hitchhackers_guide_brain/. The last link is what I believe is the correct link.
For the second one, I searched the reference on the new …
> [Fix] Fixed dead links

- neurokit2/data/data.py
Makes sure proj_id is int or None type. This shoudl fix the fact that building the docs (running "make html") gets stuck on an eeg notebook (examples/eeg_complexity/eeg_complexity.ipynb) that imports a dataset where the proj_id shows up initially as a numpy array.
Here is the [error.log](https://github.com/user-attachments/files/21498930/error.log) that leads me to believe this fix is necessary.
I have changed a call of open to with, at the point when the function interfaces with files, based on this feedback from running the code checks: "data.py:228:12: R1732: Consider using 'with' for resource-allocating operations (consider-using-with)".
I believe the last item on the checklist is not …
> [Fix] Make Sure data()'s proj_id is Int or None
